### ISSUE TITLE
Xquery Sets unsupported

### ISSUE THREAD

**Issue by koehn** [sibprogrammer/xq#26]
**Problem Statement**

Xquery Sets are unsupported. 

**Steps to Reproduce**

Given this input:
```
<bunch>
  <foo>
    <bar>abc</bar>
    <bar>def</bar>
  </foo>
  <foo>
    <bar>ghi</bar>
    <bar>jkl</bar>
  </foo>
</bunch>
```
This query should be valid: `bunch/foo[(bar)=("abc","ghi”)]`

**Actual Result**

```
panic: bunch/foo[(bar)=("abc","ghi")] has an invalid token

goroutine 18 [running]:
github.com/antchfx/xmlquery.Find(...)
        github.com/antchfx/xmlquery@v1.3.13/query.go:76
github.com/sibprogrammer/xq/internal/utils.XPathQuery({0x1031981b8?, 0x14000120000?}, {0x103198038, 0x14000120098}, {0x16d0af916, 0x1e}, 0x0)
        github.com/sibprogrammer/xq/internal/utils/utils.go:179 +0x178
github.com/sibprogrammer/xq/cmd.NewRootCmd.func1.1()
        github.com/sibprogrammer/xq/cmd/root.go:59 +0x210
created by github.com/sibprogrammer/xq/cmd.NewRootCmd.func1
        github.com/sibprogrammer/xq/cmd/root.go:55 +0x410
```

**Expected Result**
```
<foo>
    <bar>abc</bar>
    <bar>def</bar>
  </foo><foo>
    <bar>ghi</bar>
    <bar>jkl</bar>
  </foo>
```

See https://xqueryfiddle.liberty-development.net/jyyiVhs

**Comment by sibprogrammer** [comment]
The alternative syntax for that expression is the following:
```
xq -x 'bunch/foo[bar = "abc" or bar = "ghi"]' tmp/test.xml
```
And it works.
