### ISSUE TITLE
Error message for "invalid token" is confusing

### ISSUE THREAD

**Issue by scfc** [sibprogrammer/xq#28]
With `xq-1.1.3-1.fc37.x86_64` on Fedora 37, providing an invalid XPath expression leads to:

```
[tim@vagabond ~]$ xq -x '//a[b = c d]' /dev/null 
panic: //a[b = c d] has an invalid token

goroutine 6 [running]:
panic({0x55d9b1e35260, 0xc000059780})
        /usr/lib/golang/src/runtime/panic.go:987 +0x3ba fp=0xc00014de98 sp=0xc00014ddd8 pc=0x55d9b1a3471a
github.com/antchfx/xmlquery.Find(...)
        /usr/share/gocode/src/github.com/antchfx/xmlquery/query.go:76
github.com/sibprogrammer/xq/internal/utils.XPathQuery({0x55d9b1e94b98?, 0xc0000140a0?}, {0x55d9b1e949d8, 0xc0000140b0}, {0x7ffe35132014, 0xc}, 0x0)
        /builddir/build/BUILD/xq-1.1.3/_build/src/github.com/sibprogrammer/xq/internal/utils/utils.go:179 +0x1f9 fp=0xc00014df30 sp=0xc00014de98 pc=0x55d9b1c31dd9
github.com/sibprogrammer/xq/cmd.NewRootCmd.func1.1()
        /builddir/build/BUILD/xq-1.1.3/_build/src/github.com/sibprogrammer/xq/cmd/root.go:59 +0x231 fp=0xc00014dfe0 sp=0xc00014df30 pc=0x55d9b1d45271
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00014dfe8 sp=0xc00014dfe0 pc=0x55d9b1a646e1
created by github.com/sibprogrammer/xq/cmd.NewRootCmd.func1
        /builddir/build/BUILD/xq-1.1.3/_build/src/github.com/sibprogrammer/xq/cmd/root.go:55 +0x475

goroutine 1 [runnable]:
runtime.gopark(0xc00015b9c8?, 0x2?, 0xff?, 0x4f?, 0xc00015b9a4?)
        /usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc00015b828 sp=0xc00015b808 pc=0x55d9b1a37776
runtime.selectgo(0xc00015b9c8, 0xc00015b9a0, 0xc00015b9f0?, 0x0, 0x7f0595246108?, 0x1)
        /usr/lib/golang/src/runtime/select.go:328 +0x7bc fp=0xc00015b968 sp=0xc00015b828 pc=0x55d9b1a46b1c
io.(*pipe).read(0xc00006a4e0, {0xc0001c2000, 0x8000, 0xc000059701?})
        /usr/lib/golang/src/io/pipe.go:57 +0xb1 fp=0xc00015b9f8 sp=0xc00015b968 pc=0x55d9b1aa1871
io.(*PipeReader).Read(0x10?, {0xc0001c2000?, 0xc000059750?, 0x55d9b2174d20?})
        /usr/lib/golang/src/io/pipe.go:136 +0x25 fp=0xc00015ba28 sp=0xc00015b9f8 pc=0x55d9b1aa2025
io.copyBuffer({0x55d9b1e95318, 0xc000059750}, {0x55d9b1e949b8, 0xc0000140a8}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:427 +0x1b2 fp=0xc00015baa8 sp=0xc00015ba28 pc=0x55d9b1aa07d2
io.Copy(...)
        /usr/lib/golang/src/io/io.go:386
os.genericReadFrom(0x3000000000000004?, {0x55d9b1e949b8, 0xc0000140a8})
        /usr/lib/golang/src/os/file.go:162 +0x67 fp=0xc00015bb00 sp=0xc00015baa8 pc=0x55d9b1ad0887
os.(*File).ReadFrom(0xc000014018, {0x55d9b1e949b8, 0xc0000140a8})
        /usr/lib/golang/src/os/file.go:156 +0x1b0 fp=0xc00015bb50 sp=0xc00015bb00 pc=0x55d9b1ad07d0
io.copyBuffer({0x55d9b1e94bd8, 0xc000014018}, {0x55d9b1e949b8, 0xc0000140a8}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/io/io.go:413 +0x14b fp=0xc00015bbd0 sp=0xc00015bb50 pc=0x55d9b1aa076b
io.Copy(...)
        /usr/lib/golang/src/io/io.go:386
github.com/sibprogrammer/xq/internal/utils.PagerPrint({0x55d9b1e949b8?, 0xc0000140a8}, {0x55d9b1e94bd8?, 0xc000014018})
        /builddir/build/BUILD/xq-1.1.3/_build/src/github.com/sibprogrammer/xq/internal/utils/utils.go:322 +0x8a fp=0xc00015bc58 sp=0xc00015bbd0 pc=0x55d9b1c3336a
github.com/sibprogrammer/xq/cmd.NewRootCmd.func1(0xc0001ba000, {0xc000101f80, 0x1, 0x3?})
        /builddir/build/BUILD/xq-1.1.3/_build/src/github.com/sibprogrammer/xq/cmd/root.go:81 +0x4a7 fp=0xc00015bd10 sp=0xc00015bc58 pc=0x55d9b1d44fc7
github.com/spf13/cobra.(*Command).execute(0xc0001ba000, {0xc000016090, 0x3, 0x3})
        /usr/share/gocode/src/github.com/spf13/cobra/command.go:916 +0x862 fp=0xc00015be48 sp=0xc00015bd10 pc=0x55d9b1c85aa2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001ba000)
        /usr/share/gocode/src/github.com/spf13/cobra/command.go:1044 +0x3bd fp=0xc00015bf00 sp=0xc00015be48 pc=0x55d9b1c8631d
github.com/spf13/cobra.(*Command).Execute(...)
        /usr/share/gocode/src/github.com/spf13/cobra/command.go:968
github.com/sibprogrammer/xq/cmd.Execute()
        /builddir/build/BUILD/xq-1.1.3/_build/src/github.com/sibprogrammer/xq/cmd/root.go:112 +0x31 fp=0xc00015bf18 sp=0xc00015bf00 pc=0x55d9b1d45951
main.main()
        /builddir/build/BUILD/xq-1.1.3/_build/src/github.com/sibprogrammer/xq/main.go:16 +0xe5 fp=0xc00015bf80 sp=0xc00015bf18 pc=0x55d9b1d46145
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:250 +0x213 fp=0xc00015bfe0 sp=0xc00015bf80 pc=0x55d9b1a373b3
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00015bfe8 sp=0xc00015bfe0 pc=0x55d9b1a646e1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000042fb0 sp=0xc000042f90 pc=0x55d9b1a37776
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:369
runtime.forcegchelper()
        /usr/lib/golang/src/runtime/proc.go:302 +0xad fp=0xc000042fe0 sp=0xc000042fb0 pc=0x55d9b1a3760d
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000042fe8 sp=0xc000042fe0 pc=0x55d9b1a646e1
created by runtime.init.7
        /usr/lib/golang/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000043790 sp=0xc000043770 pc=0x55d9b1a37776
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /usr/lib/golang/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000437c8 sp=0xc000043790 pc=0x55d9b1a2406e
runtime.gcenable.func1()
        /usr/lib/golang/src/runtime/mgc.go:178 +0x26 fp=0xc0000437e0 sp=0xc0000437c8 pc=0x55d9b1a18d06
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000437e8 sp=0xc0000437e0 pc=0x55d9b1a646e1
created by runtime.gcenable
        /usr/lib/golang/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000020070?, 0x55d9b1df0768?, 0x1?, 0x0?, 0x0?)
        /usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000043f70 sp=0xc000043f50 pc=0x55d9b1a37776
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x55d9b21747a0)
        /usr/lib/golang/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000043fa0 sp=0xc000043f70 pc=0x55d9b1a22113
runtime.bgscavenge(0x0?)
        /usr/lib/golang/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000043fc8 sp=0xc000043fa0 pc=0x55d9b1a226e5
runtime.gcenable.func2()
        /usr/lib/golang/src/runtime/mgc.go:179 +0x26 fp=0xc000043fe0 sp=0xc000043fc8 pc=0x55d9b1a18ca6
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000043fe8 sp=0xc000043fe0 pc=0x55d9b1a646e1
created by runtime.gcenable
        /usr/lib/golang/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x55d9b2174d20?, 0xc000007860?, 0x0?, 0x0?, 0xc000042770?)
        /usr/lib/golang/src/runtime/proc.go:363 +0xd6 fp=0xc000042628 sp=0xc000042608 pc=0x55d9b1a37776
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:369
runtime.runfinq()
        /usr/lib/golang/src/runtime/mfinal.go:180 +0x10f fp=0xc0000427e0 sp=0xc000042628 pc=0x55d9b1a17e0f
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000427e8 sp=0xc0000427e0 pc=0x55d9b1a646e1
created by runtime.createfing
        /usr/lib/golang/src/runtime/mfinal.go:157 +0x45
Abgebrochen (Speicherabzug geschrieben)
[tim@vagabond ~]$
```

At first, I thought that `xq` had simply crashed because the wall of text hid the `panic: //a[b = c d] has an invalid token` line that showed that `xq` had realized that something was amiss :-).

I would prefer and except an error message similiar to `jq`'s and other programs':

```
[tim@vagabond ~]$ jq 'undefined()' /dev/null 
jq: error: syntax error, unexpected ')' (Unix shell quoting issues?) at <top-level>, line 1:
undefined()          
jq: 1 compile error
[tim@vagabond ~]$
```

**Comment by sibprogrammer** [comment]
@scfc Thank you for your report!
